# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(291, 481)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.predict_button = QtWidgets.QPushButton(self.centralwidget)
        self.predict_button.setGeometry(QtCore.QRect(20, 370, 91, 91))
        self.predict_button.setObjectName("predict_button")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(120, 370, 151, 91))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.results_layout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.results_layout.setContentsMargins(0, 0, 0, 0)
        self.results_layout.setObjectName("results_layout")
        self.actual_age_textBrowser = QtWidgets.QTextBrowser(self.formLayoutWidget)
        self.actual_age_textBrowser.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse)
        self.actual_age_textBrowser.setObjectName("actual_age_textBrowser")
        self.results_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.actual_age_textBrowser)
        self.gender_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.gender_label.setObjectName("gender_label")
        self.results_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.gender_label)
        self.gender_textBrowser = QtWidgets.QTextBrowser(self.formLayoutWidget)
        self.gender_textBrowser.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse)
        self.gender_textBrowser.setObjectName("gender_textBrowser")
        self.results_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.gender_textBrowser)
        self.predicted_age_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.predicted_age_label.setObjectName("predicted_age_label")
        self.results_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.predicted_age_label)
        self.predicted_age_textBrowser = QtWidgets.QTextBrowser(self.formLayoutWidget)
        self.predicted_age_textBrowser.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse)
        self.predicted_age_textBrowser.setObjectName("predicted_age_textBrowser")
        self.results_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.predicted_age_textBrowser)
        self.actual_age_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.actual_age_label.setObjectName("actual_age_label")
        self.results_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.actual_age_label)
        self.image_pixmap = QtWidgets.QLabel(self.centralwidget)
        self.image_pixmap.setGeometry(QtCore.QRect(20, 90, 255, 255))
        self.image_pixmap.setFrameShape(QtWidgets.QFrame.Box)
        self.image_pixmap.setText("")
        self.image_pixmap.setPixmap(QtGui.QPixmap("data/noImageSelected.jpg"))
        self.image_pixmap.setScaledContents(True)
        self.image_pixmap.setObjectName("image_pixmap")
        self.select_image_button = QtWidgets.QPushButton(self.centralwidget)
        self.select_image_button.setGeometry(QtCore.QRect(20, 10, 256, 23))
        self.select_image_button.setObjectName("select_image_button")
        self.path_scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.path_scrollArea.setGeometry(QtCore.QRect(20, 40, 256, 41))
        self.path_scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.path_scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.path_scrollArea.setWidgetResizable(True)
        self.path_scrollArea.setObjectName("path_scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 254, 31))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.image_path_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.image_path_label.setText("")
        self.image_path_label.setObjectName("image_path_label")
        self.horizontalLayout.addWidget(self.image_path_label)
        self.path_scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SRLM_Project"))
        self.predict_button.setText(_translate("MainWindow", "Predict"))
        self.actual_age_textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.gender_label.setText(_translate("MainWindow", "Gender:"))
        self.gender_textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.predicted_age_label.setText(_translate("MainWindow", "Predicted Age:"))
        self.predicted_age_textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.actual_age_label.setText(_translate("MainWindow", "Actual Age:"))
        self.select_image_button.setText(_translate("MainWindow", "Select Image"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
